package com.example.demo.dto;

import java.time.LocalDate;

import com.example.demo.enums.UserStatus;
import jakarta.validation.constraints.*;

public class UserRequestDto {

    @NotBlank(message = "First name is required")
    @Size(min = 2, max = 50)
    private String firstName;

    @NotBlank(message = "Last name is required")
    @Size(min = 2, max = 50)
    private String lastName;

    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    private String email;

    @NotBlank(message = "Phone number is required")
    @Pattern(
            regexp = "^[6-9]\\d{9}$",
            message = "Invalid phone number"
    )
    private String phoneNumber;

    @NotBlank(message = "Department is required")
    @Size(max = 50, message = "Department cannot exceed 50 characters")
    private String department;

    @NotBlank(message = "Designation is required")
    @Size(max = 50, message = "Designation cannot exceed 50 characters")
    private String designation;

    @NotNull
    @Positive(message = "Salary must be positive")
    private Double salary;

    @NotNull(message = "Joining date is required")
    @PastOrPresent(message = "Joining date cannot be in the future")
    private LocalDate joiningDate;

    @NotNull(message = "Status is required")
    private UserStatus status;

    public UserRequestDto(){}

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getDepartment() {
        return department;
    }
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getDesignation() {
        return designation;
    }
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public Double getSalary() {
        return salary;
    }
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public LocalDate getJoiningDate() {
        return joiningDate;
    }
    public void setJoiningDate(LocalDate joiningDate) {
        this.joiningDate = joiningDate;
    }

    public UserStatus getStatus() {
        return status;
    }
    public void setStatus(UserStatus status) {
        this.status = status;
    }


}
    //Don't keep createdAt and updatedAt in Request DTO
    //These are generated by your entity's:

/*Why Validation is Needed??
Prevent invalid data from entering the application.
Validate input before saving to the database.*/

/*
1. @NotNull
Checks only that the value is not null.

@NotNull
private String name;
Valid : "name" , "" , "   "
Invalid : null
Only null is rejected.

2. @NotEmpty
Checks: Not null , Length > 0

@NotEmpty
private String name;
Valid : "name" , "   "
Invalid : null , ""

Notice:
"   "  : (only spaces) is still valid because its length is greater than 0.

3. @NotBlank
Checks: Not null , Not empty , Not only whitespace

@NotBlank
private String name;
Valid : "name" , " Surjeet "
Invalid : null , "" , "     "
This is usually the best choice for names, departments, designations, etc.
*/