package com.example.demo.controller;

import com.example.demo.dto.UserRequestDto;
import com.example.demo.dto.UserResponseDto;
import com.example.demo.service.UserService;
import jakarta.validation.Valid;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/users")
public class UserController {

    private final UserService userService; //Encapsulation , access modifier used "private"

    public UserController(UserService userService) {
        this.userService = userService;
    }

    @PostMapping("/saveUser")
    public UserResponseDto saveUser(
            @Valid @RequestBody UserRequestDto requestDto) {
        return userService.saveUser(requestDto);
    }

    @GetMapping("/fetchUsers")
    public List<UserResponseDto> fetchUsers() {
        return userService.fetchUsers();
    }

    @GetMapping("/fetchUser/{id}")
    public UserResponseDto fetchUser(@PathVariable Long id) {
        return userService.fetchUser(id);
    }

    @PutMapping("/{id}")
    public UserResponseDto updateUser(
            @PathVariable Long id,
            @Valid @RequestBody UserRequestDto requestDto) {

        return userService.updateUser(id, requestDto);
    }

    @DeleteMapping("/{id}")
    public void deleteUser(@PathVariable Long id) {
        userService.deleteUser(id);
    }

    @DeleteMapping("/deleteAll")
    public void deleteAllUsers() {
        userService.deleteAllUsers();
    }
}
/*
Generally validation is applied on RequestDto, not on ResponseDto.
Why RequestDto?
Because it contains data coming from the client and that data may be invalid.

@PostMapping
public UserResponseDto saveUser(
        @Valid @RequestBody UserRequestDto requestDto) {
}
Here Spring validates what the user sends.

Why not ResponseDto?
Because the response is generated by your application, so you control that data already.
UserResponseDto response = new UserResponseDto();
response.setFirstName(user.getFirstName());
Normally no validation is needed.

@Valid is mainly used on methods that receive data from the client and need validation before processing.
*/
